.gitignore, Flow-Control/Busy-Wait-Button/README.md, Flow-Control/Busy-Wait-Button/main.cpp, Flow-Control/Busy-Wait-Button/mbed-os.lib, Flow-Control/Busy-Wait/README.md, Flow-Control/Busy-Wait/main.cpp, Flow-Control/Busy-Wait/mbed-os.lib, Flow-Control/Interrupt-Button/README.md, Flow-Control/Interrupt-Button/main.cpp, Flow-Control/Interrupt-Button/mbed-os.lib, Flow-Control/README.md, Flow-Control/Thread/README.md, Flow-Control/Thread/main.cpp, Flow-Control/Thread/mbed-os.lib, Flow-Control/Ticker/README.md, Flow-Control/Ticker/main.cpp, Flow-Control/Ticker/mbed-os.lib, IdleLoop/mbed-os.lib
* Also added Mbed OS lib to IdleLoop
* Also added a .gitignore file to this repo for library/file management
=> Add "Application Flow Control" examples and READMEs

EventFlags/README.md, EventFlags/main.cpp, EventFlags/mbed-os.lib
Move the `EventFlags` example from https://github.com/ARMmbed/mbed-os-5-docs/blob/development/docs/api/rtos/EventFlags.md and update the code.
=> Move & update EventFlags example from docs repo

CellularTCP/main.cpp, CellularTCP/mbed-os.lib
moving code from : https://github.com/ithinuel/mbed-os-5-docs/blob/new_engine/docs/tutorials/using_apis/connectivity/cellular_tcp.md
=> Move example code from the doc

TLSSocket/main.cpp, TLSSocket/mbed-os.lib, TLSSocket/mbed_app.json
This is nearly a verbatim copy of Socket examples, but now uses TLSSocket.
=> Add TLSSocket example

Alarm/README.md, Alarm/main.cpp, Alarm/mbed-os.lib
Moving examples here as our per our group discussion @cmonr @AnotherButler 
mbed-os.lib is currently pointing to master.
=> Add Alarm example to docs

QSPI/main.cpp
For the Nordic nRF52x platform, the QSPI flash memory address and the total flash buffer size need to be DWORD/4-byte aligned. This PR updates the main.cpp example file in the documents to match the updates to the example code that were implemented in this PR: https://github.com/ARMmbed/mbed-os-example-qspi/pull/2
[X] Fix
[ ] Refactor
[ ] Target update
[ ] Functionality change
[ ] Docs update
[ ] Test update
[ ] Breaking change
=> Update the qspi example for Nordic nRF52x targets

CellularTCP/main.cpp
Reverts ARMmbed/mbed-os-examples-docs_only#33
Revert because 5.11 still points to it.
=> Revert "Delete main.cpp"

CellularTCP/mbed-os.lib
Reverts ARMmbed/mbed-os-examples-docs_only#34
Revert because 5.11 still uses this.
=> Revert "Delete mbed-os.lib"

APIs_Drivers/BufferedSerial_echo/main.cpp, APIs_Drivers/BufferedSerial_printf/main.cpp, APIs_Drivers/UnbufferedSerial/main.cpp
The code snippets are to be referenced in the API documentation for the classes.
=> Add code snippet for UnbufferedSerial and BufferedSerial API documentation

APIs_RTOS/Basic/README.md, APIs_RTOS/Basic/main.cpp, APIs_RTOS/Flags/README.md, APIs_RTOS/Flags/main.cpp, APIs_RTOS/Isr/README.md, APIs_RTOS/Isr/main.cpp, APIs_RTOS/Mail/README.md, APIs_RTOS/Mail/main.cpp, APIs_RTOS/Mutex/README.md, APIs_RTOS/Mutex/main.cpp, APIs_RTOS/Semaphore/README.md, APIs_RTOS/Semaphore/main.cpp, APIs_RTOS/Threading_with_callback/README.md, APIs_RTOS/Threading_with_callback/main.cpp
Move examples:
https://os.mbed.com/teams/mbed_example/code/rtos_basic/
https://os.mbed.com/teams/mbed_example/code/rtos_mail/
https://os.mbed.com/teams/mbed_example/code/rtos_mutex/
https://os.mbed.com/teams/mbed_example/code/rtos_signals/
https://os.mbed.com/teams/mbed_example/code/rtos_threading_with_callback/
https://os.mbed.com/teams/mbed_example/code/rtos_isr/
https://os.mbed.com/teams/mbed_example/code/rtos_semaphore/
to this repo
Docs update PR: https://github.com/ARMmbed/mbed-os-5-docs/pull/1240
=> add RTOS examples

APIs_RTOS/EventQueue_ex_1/main.cpp, APIs_RTOS/EventQueue_ex_2/README.md, APIs_RTOS/EventQueue_ex_2/main.cpp, APIs_RTOS/EventQueue_ex_3/README.md, APIs_RTOS/EventQueue_ex_3/main.cpp, APIs_RTOS/Shared_Events_1/README.md, APIs_RTOS/Shared_Events_1/main.cpp, APIs_RTOS/Shared_Events_2/README.md, APIs_RTOS/Shared_Events_2/main.cpp, APIs_RTOS/Shared_Events_2/mbed_app.json, APIs_RTOS/mbed-os-example-events/README.md, APIs_RTOS/mbed-os-example-events/main.cpp
Move examples:
https://os.mbed.com/teams/mbed_example/code/events_ex_2/
https://os.mbed.com/teams/mbed_example/code/events_ex_3/
https://os.mbed.com/teams/mbed_example/code/Shared_Events_1/
https://os.mbed.com/teams/mbed_example/code/Shared_Events_2/
https://os.mbed.com/teams/mbed_example/code/mbed-os-example-events/
to this repo
Docs update PR: https://github.com/ARMmbed/mbed-os-5-docs/pull/1245
=> add Events examples

APIs_Platform/DeepSleepLock_Example_1/README.md, APIs_Platform/DeepSleepLock_Example_1/main.cpp, APIs_Platform/SleepManager_Example_1/README.md, APIs_Platform/SleepManager_Example_1/main.cpp
Move examples:
https://os.mbed.com/teams/mbed_example/code/DeepSleepLock_Example_1/
https://os.mbed.com/teams/mbed_example/code/SleepManager_Example_1/
to this repo
Docs update PR: https://github.com/ARMmbed/mbed-os-5-docs/pull/1247
=> add Sleep examples

APIs_Platform/time_HelloWorld/README.md, APIs_Platform/time_HelloWorld/main.cpp
Move examples:
https://os.mbed.com/teams/mbed_example/code/time_HelloWorld/
to this repo
Docs update PR: https://github.com/ARMmbed/mbed-os-5-docs/pull/1248
=> add Time example

APIs_Drivers/Ticker_Example/README.md, APIs_Drivers/Ticker_Example/main.cpp, APIs_Drivers/Ticker_HelloWorld/README.md, APIs_Drivers/Ticker_HelloWorld/main.cpp, APIs_Drivers/Timeout_Example/README.md, APIs_Drivers/Timeout_Example/main.cpp, APIs_Drivers/Timeout_HelloWorld/README.md, APIs_Drivers/Timeout_HelloWorld/main.cpp, APIs_Drivers/Timer_HelloWorld/README.md, APIs_Drivers/Timer_HelloWorld/main.cpp
Move examples:
https://os.mbed.com/teams/mbed_example/code/Timeout_HelloWorld/
https://os.mbed.com/teams/mbed_example/code/Timeout_Example/
https://os.mbed.com/teams/mbed_example/code/Ticker_HelloWorld/
https://os.mbed.com/teams/mbed_example/code/Ticker_Example/
https://os.mbed.com/teams/mbed_example/code/Timer_HelloWorld/
to this repo
Docs update PR: https://github.com/ARMmbed/mbed-os-5-docs/pull/1251
=> add Ticker examples

APIs_Platform/Heap_Stats_ex_1/README.md, APIs_Platform/Heap_Stats_ex_1/main.cpp, APIs_Platform/Heap_Stats_ex_1/mbed_app.json, APIs_Platform/Stack_Stats_ex_1/README.md, APIs_Platform/Stack_Stats_ex_1/main.cpp, APIs_Platform/Stack_Stats_ex_1/mbed_app.json
Move examples:
https://os.mbed.com/teams/mbed_example/code/stack_stats_example/
https://os.mbed.com/teams/mbed_example/code/heap_stats_example/
https://os.mbed.com/teams/mbed_example/code/memory_tracing_example/
to this repo
Docs update PR: https://github.com/ARMmbed/mbed-os-5-docs/pull/1262
=> add memory stats examples

APIs_Drivers/BufferedSerial_echo/main.cpp, APIs_Drivers/BufferedSerial_printf/main.cpp, APIs_Drivers/QSPI/main.cpp, APIs_Drivers/UnbufferedSerial/main.cpp, APIs_RTOS/EventQueue_ex_1/main.cpp, APIs_RTOS/Kernel_get_ms_count/main.cpp, APIs_RTOS/UserAllocatedEvent_ex_1/main.cpp, APIs_Security/DeviceKey/main.cpp, APIs_Storage/BlockDevice/main.cpp, APIs_Storage/BufferedBlockDevice/main.cpp, APIs_Storage/FlashIAPBlockDevice/main.cpp, APIs_Storage/FlashSimBlockDevice/main.cpp, APIs_Storage/MBRBlockDevice_ex_1/main.cpp, APIs_Storage/MBRBlockDevice_ex_2/main.cpp, APIs_Storage/ProfilingBlockDevice/main.cpp, APIs_Storage/SDBlockDevice/main.cpp, APIs_Storage/SPIFBlockDevice/main.cpp, APIs_Storage/SlicingBlockDevice/main.cpp, Porting_process/Direct-Register-Blinky/main.cpp, Tutorials_Overview/IdleLoop/main.cpp, Tutorials_UsingAPIs/Alarm/main.cpp, Tutorials_UsingAPIs/Flow-Control-Busy-Wait-Button/main.cpp, Tutorials_UsingAPIs/Flow-Control-Busy-Wait/main.cpp, Tutorials_UsingAPIs/Flow-Control-Interrupt-Button/main.cpp, Tutorials_UsingAPIs/Flow-Control-Thread/main.cpp, Tutorials_UsingAPIs/Flow-Control-Ticker/main.cpp
Applying astyle to all files.
later an astyle check would be added in CI
=> Refactor for applying astyle reformat

APIs_Platform/Memory_tracing_ex_1/README.md, APIs_Platform/Memory_tracing_ex_1/main.cpp, APIs_Platform/Memory_tracing_ex_1/mbed_app.json
Move examples:
https://os.mbed.com/teams/mbed_example/code/memory_tracing_example/
to this repo
Docs update PR: https://github.com/ARMmbed/mbed-os-5-docs/pull/1262
=> add memory trace example

APIs_Drivers/AnalogIn_ex_1/README.md, APIs_Drivers/AnalogIn_ex_1/main.cpp, APIs_Drivers/AnalogIn_ex_2/README.md, APIs_Drivers/AnalogIn_ex_2/main.cpp, APIs_Drivers/AnalogIn_ex_3/README.md, APIs_Drivers/AnalogIn_ex_3/main.cpp, APIs_Drivers/AnalogOut_ex_1/README.md, APIs_Drivers/AnalogOut_ex_1/main.cpp, APIs_Drivers/AnalogOut_ex_2/README.md, APIs_Drivers/AnalogOut_ex_2/main.cpp
Move examples:
https://os.mbed.com/teams/mbed_example/code/AnalogIn_HelloWorld/
https://os.mbed.com/teams/mbed_example/code/AnalogOut_HelloWorld/
https://os.mbed.com/teams/mbed_example/code/AnalogIn_ex_1/
https://os.mbed.com/teams/mbed_example/code/AnalogIn_ex_2/
https://os.mbed.com/teams/mbed_example/code/AnalogOut_ex_1/
to this repo
Docs update PR: https://github.com/ARMmbed/mbed-os-5-docs/pull/1265
=> add Analog In/Out examples

APIs_Drivers/PwmOut_ex_1/README.md, APIs_Drivers/PwmOut_ex_1/main.cpp, APIs_Drivers/PwmOut_ex_2/README.md, APIs_Drivers/PwmOut_ex_2/main.cpp, APIs_Drivers/PwmOut_ex_3/README.md, APIs_Drivers/PwmOut_ex_3/main.cpp
Move examples:
https://os.mbed.com/teams/mbed_example/code/PwmOut_HelloWorld/
https://os.mbed.com/teams/mbed_example/code/PwmOut_ex_1/
https://os.mbed.com/teams/mbed_example/code/PwmOut_ex_2/
to this repo
Docs update PR: https://github.com/ARMmbed/mbed-os-5-docs/pull/1269
=> add PwmOut examples

APIs_Drivers/InterruptIn_ex_1/README.md, APIs_Drivers/InterruptIn_ex_1/main.cpp, APIs_Drivers/InterruptIn_ex_2/README.md, APIs_Drivers/InterruptIn_ex_2/main.cpp
Move examples:
https://os.mbed.com/teams/mbed_example/code/InterruptIn_ex_1/
https://os.mbed.com/teams/mbed_example/code/InterruptIn_HelloWorld/
to this repo
Docs update PR: https://github.com/ARMmbed/mbed-os-5-docs/pull/1268
=> add InterruptIn examples

APIs_Storage/ChainingBlockDevice_ex_1/README.md, APIs_Storage/ChainingBlockDevice_ex_1/main.cpp, APIs_Storage/ChainingBlockDevice_ex_2/README.md, APIs_Storage/ChainingBlockDevice_ex_2/main.cpp, APIs_Storage/HeapBlockDevice_ex_1/README.md, APIs_Storage/HeapBlockDevice_ex_1/main.cpp, APIs_Storage/MBRBlockDevice_ex_1/README.md, APIs_Storage/MBRBlockDevice_ex_1/main.cpp, APIs_Storage/MBRBlockDevice_ex_2/README.md, APIs_Storage/MBRBlockDevice_ex_2/main.cpp, APIs_Storage/ProfilingBlockDevice/README.md, APIs_Storage/ProfilingBlockDevice/main.cpp, APIs_Storage/SlicingBlockDevice/README.md, APIs_Storage/SlicingBlockDevice/main.cpp
Move examples:
https://os.mbed.com/teams/mbed_example/code/HeapBlockDevice_ex_1/
https://os.mbed.com/teams/mbed_example/code/ChainingBlockDevice_ex_1/
https://os.mbed.com/teams/mbed_example/code/ChainingBlockDevice_ex_2/
to this repo
Update examples:
https://os.mbed.com/teams/mbed_example/code/MBRBlockDevice_ex_1/
https://os.mbed.com/teams/mbed_example/code/MBRBlockDevice_ex_2/
https://os.mbed.com/teams/mbed_example/code/ProfilingBlockDevice_ex_1/
https://os.mbed.com/teams/mbed_example/code/SlicingBlockDevice_ex_1/
Docs update PR: https://github.com/ARMmbed/mbed-os-5-docs/pull/1273
=> add BlockDevices examples

APIs_Drivers/I2C_ex_1/README.md, APIs_Drivers/I2C_ex_1/main.cpp
Move examples:
https://os.mbed.com/teams/mbed_example/code/I2C_HelloWorld/
to this repo
Docs update PR: https://github.com/ARMmbed/mbed-os-5-docs/pull/1274
=> add I2C example

APIs_Drivers/lowpowerTicker_ex_1/README.md, APIs_Drivers/lowpowerTicker_ex_1/main.cpp, APIs_Drivers/lowpowerTimeout_ex_1/README.md, APIs_Drivers/lowpowerTimeout_ex_1/main.cpp, APIs_Drivers/lowpowerTimer_ex_1/README.md, APIs_Drivers/lowpowerTimer_ex_1/main.cpp
Move examples:
https://os.mbed.com/teams/mbed_example/code/LowPowerTimeout-example/
https://os.mbed.com/teams/mbed_example/code/LowPowerTimer-example/
https://os.mbed.com/teams/mbed_example/code/LowPowerTicker_HelloWorld/
to this repo
Docs update PR: https://github.com/ARMmbed/mbed-os-5-docs/pull/1252
=> add LowPowerTicker examples

APIs_Platform/CircularBuffer_ex_1/README.md, APIs_Platform/CircularBuffer_ex_1/main.cpp, APIs_Platform/CriticalSectionLock_ex_1/README.md, APIs_Platform/CriticalSectionLock_ex_1/main.cpp, APIs_Platform/PlatformMutex_ex_1/README.md, APIs_Platform/PlatformMutex_ex_1/main.cpp, APIs_Platform/Utils_ex_1/README.md, APIs_Platform/Utils_ex_1/main.cpp
Move examples:
https://os.mbed.com/teams/mbed_example/code/mbed-os-example-platform-mutex/
https://os.mbed.com/teams/mbed_example/code/mbed-os-example-platform-utils/
https://os.mbed.com/teams/mbed_example/code/mbed-os-example-critical-section/
https://os.mbed.com/teams/mbed_example/code/mbed-os-example-circular-buffer/
to this repo
Docs update PR: https://github.com/ARMmbed/mbed-os-5-docs/pull/1271
=> add platform utils examples

APIs_Drivers/CAN_ex_1/README.md, APIs_Drivers/CAN_ex_1/main.cpp, APIs_Drivers/CAN_ex_1/mbed_app.json
Move examples:
https://os.mbed.com/teams/mbed_example/code/CAN_ex_1/
to this repo
Docs update PR: https://github.com/ARMmbed/mbed-os-5-docs/pull/1278
=> add CAN example

APIs_Platform/FileHandle/README.md, APIs_Platform/FileHandle/main.cpp, APIs_Platform/FileHandle_sigio/README.md, APIs_Platform/FileHandle_sigio/main.cpp, APIs_Platform/Poll/README.md, APIs_Platform/Poll/main.cpp, APIs_Platform/Poll/mbed_app.json, APIs_Platform/ScopedRamExecutionLock/README.md, APIs_Platform/ScopedRamExecutionLock/main.cpp, APIs_Platform/ScopedRomWriteLock/README.md, APIs_Platform/ScopedRomWriteLock/main.cpp, APIs_Platform/Shared_pointer/README.md, APIs_Platform/Shared_pointer/main.cpp, APIs_Platform/Span_c/README.md, APIs_Platform/Span_c/main.cpp, APIs_Platform/Span_cpp/README.md, APIs_Platform/Span_cpp/main.cpp, test.json
Bring platform layer examples +readme files.
=> Bring platform layer examples

APIs_Platform/Callback_SerialPassthrough/main.cpp, APIs_Platform/PlatfromOverview_Callbacks/main.cpp, Tutorials_Debugging/DebugPrintf_BlinksLED/main.cpp, Tutorials_Debugging/DebugPrintf_SetBaudRate/main.cpp, Tutorials_SerialComm/Serial_EchoBack/main.cpp, Tutorials_SerialComm/Serial_HelloWorld/main.cpp, Tutorials_SerialComm/Serial_LEDControl/main.cpp, Tutorials_SerialComm/Serial_PassCharacters/main.cpp, Tutorials_SerialComm/Serial_ReadToBuffer/main.cpp, Tutorials_SerialComm/Serial_STDOUT/main.cpp
move the code snippets from:
https://os.mbed.com/docs/mbed-os/v5.15/tutorials/serial-comm.html
to this repo.
link updates via https://github.com/ARMmbed/mbed-os-5-docs/pull/1283
=> add serial communication snippets

APIs_RTOS/EventQueue_ex_2/main.cpp
This is needed for https://github.com/ARMmbed/mbed-os-5-docs/pull/1321
=> EventQueue_ex_2: dispatch_forever() is more readable than dispatch()

APIs_Drivers/Timer_HelloWorld/main.cpp, APIs_Drivers/lowpowerTimer_ex_1/main.cpp
Thanks to feedbacks from the community, we update timer examples to use chrono values.
Also change to print integer milliseconds (~ order of 10ms) instead of seconds as the new API does not use floating points.
=> Fix deprecated Timer and LowPowerTimer read() usages

APIs_Platform/AT_CmdParser/README.md, APIs_Platform/AT_CmdParser/main.cpp, APIs_USB/USBHID/main.cpp
For consistency, all snippets used in Mbed docs should be stored here. This moves source from https://github.com/ARMmbed/mbed-os-example-atcmdparser. The snippet is referenced here https://os.mbed.com/docs/mbed-os/v6.4/apis/atcmdparser.html. 
* Source builds but no hardware tests done as I don't have a compatible WiFi module for the snippet  
----------------------------------------------------------------------------------------------------------------
[x] No Tests required for this change (E.g docs only update)
[] Covered by existing mbed-os tests (Greentea or Unittest)
[] Tests / results supplied as part of this PR
=> Add AT command parser example to docs

APIs_RTOS/ThisThread_Blinky/README.md, APIs_RTOS/ThisThread_Blinky/main.cpp
For consistency, all snippets used in Mbed docs should be stored here. This moves source from https://github.com/ARMmbed/mbed-os-example-thisthread/. This snippet is referenced here: https://os.mbed.com/docs/mbed-os/v6.4/apis/thisthread.html.
=> Add threading blinky example

APIs_RTOS/Events_ex_1/main.cpp
Also show how to use non_periodic periods and cancel() function.
=> Update Events example to use Chrono times

APIs_RTOS/EventQueue_ex_2/main.cpp, APIs_RTOS/EventQueue_ex_3/main.cpp, APIs_RTOS/Events_ex_1/main.cpp, APIs_RTOS/UserAllocatedEvent_ex_1/main.cpp
https://github.com/ARMmbed/mbed-os/pull/13975 updates the EventQueue dispatch API to 
1) move it to using chrono times and bring it inline with the rest of the code
2) Separates the API into 3 distinct functions
a) dispatch_for(duration ms)
b) dispatch_once()
c) dispatch_forever()
This PR updates the example snippets to mirror this functionality.
=> Update Event/EventQueue snippets to mirror updates to the API changes

Tutorials_SerialComm/Serial_EchoBack/main.cpp
`sizeof(buff)` is `4` because buff is a `char*`.
Fixed by removing the unnecessary pointer construct.
=> fix Serial_echoback
